version: "3.8"

services:
  bot:
    build:
      context: .
    environment:
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - TG_ADMIN_ID=${TG_ADMIN_ID}
      - API_BASE_URL=${API_BASE_URL}
    restart: always
