name: Deployment

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Remove existing project directory
        run: |
          if [ -d "$HOME/unikum_bot" ]; then
            rm -rf $HOME/unikum_bot
          fi

      - name: Clone repository
        run: |
          git clone https://github.com/awaynell/unikum_bot.git $HOME/unikum_bot

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > $HOME/unikum_bot/.env

      - name: Stop and remove containers, networks
        run: |
          cd $HOME/unikum_bot
          docker-compose down || true # Игнорируем ошибку, если контейнеров нет

      - name: Remove unused data
        run: docker system prune -a -f

      - name: Start docker-compose
        run: |
          cd $HOME/unikum_bot
          docker-compose up -d
