name: Deployment

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Stop and remove containers, networks
        run: |
          if [ -d "$HOME/unikum_bot" ]; then
            cd $HOME/unikum_bot
            docker-compose down || true # Игнорируем ошибку, если контейнеров нет
            sudo rm -rf $HOME/unikum_bot
          fi

      - name: Remove unused data
        run: docker system prune -a -f

      - name: Clone repository
        run: |
          git clone https://github.com/awaynell/unikum_bot.git $HOME/unikum_bot

      - name: Create .env file
        run: |
          echo "TG_BOT_TOKEN=${{ secrets.TG_BOT_TOKEN }}" >> /home/user/unikum_bot/.env
          echo "TG_ADMIN_ID=${{ secrets.TG_ADMIN_ID }}" >> /home/user/unikum_bot/.env
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" >> /home/user/unikum_bot/.env

      - name: Start docker-compose
        run: |
          cd $HOME/unikum_bot
          docker-compose up -d --build
